version: '3.7'

services:
  web:
    build: .
    container_name: php-web-app
    ports:
      - "8080:80"
    environment:
      - LOGS_BUCKET=${LOGS_BUCKET}  # Define the Google Cloud Storage bucket name (or leave blank if using Cloud Logging only)
      - LOGGING_BEHAVIOR=${LOGGING_BEHAVIOR:-CLOUD_LOGGING_ONLY}  # Default to CLOUD_LOGGING_ONLY, or change it to REGIONAL_USER_OWNED_BUCKET
      - GOOGLE_APPLICATION_CREDENTIALS=/path/to/your/service-account-key.json  # Path to Google Cloud service account key
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: app_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
